settings:
  docker:
    parent_image: 992382797823.dkr.ecr.eu-central-1.amazonaws.com/zenml-rlwlcs:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  user_full_name: Neural Empowerment # [First Name(s)] [Last Name]
  links:
    # Github
    - https://github.com/NeuralEmpowerment/LLM-Engineers-Handbook